### ISSUE TITLE
CAC Bypass issue

### ISSUE THREAD

**Issue by ghost** [notcake/cac-administration#1]
http://www.mpgh.net/forum/showthread.php?t=996710

debug.lua filename bypass...

would this be fix for it?:
serverside code:
local orig = file.Read("lua/includes/extensions/debug.lua")

then client:
local bp = file.Read("lua/includes/extensions/debug.lua")

and doing comparison between server and client:
if (bp == orig) then
//nothing
else
LocalPlayer():Kick()
end if

**Comment by bmwalters** [comment]
You'd have to trust the client to send you the proper hash or contents of the file.

Also it's a joke.
